#!/bin/sh
set +o posix;

vim=$(vim -e -T dumb --cmd 'exe "set t_cm=\<C-M>"|echo $VIMRUNTIME|quit' | tr -d '\r')
syn=syntax/vim.vim

filepath="$vim/$syn"

# File doesn't exist; bail
[ ! -f "$filepath" ] && {
	echo "File $syn not found in $vim";
	exit 2;
}

cd $(dirname "$0")
./update-keywords.js "$filepath"
cp "$filepath" ../tests/vim-syntax.vim
